### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by polm** [chadkirby/Articles#4]
Could you please update the version of this on npm? The one currently on there doesn't work with browserify for some reason - the `require('articledata')` in `Article.js` can't find the json file. I see in the latest version that's gone, so it'd be great to have that available on npm.

**Comment by jdesrosiers** [comment]
This project appears dead, but giving it a bump just in case it makes a difference. @chadkirby, all we need is the latest code deployed to NPM. Thanks!

**Comment by chadkirby** [comment]
Thanks for the bump. I completely missed this issue.

**Comment by chadkirby** [comment]
Ok, sorry for the inattention. I just published a new version on npm.

**Comment by jdesrosiers** [comment]
Wow! Thanks for the quick response. I tried it out this morning and it works perfectly!
